#!/bin/bash
[ -z "$1" ] && n=1 || n=$1

if [ -z "$2" ]; then
 awk '{x=x+$'$n'} END {print x}'
else
 shift
 groupby="$(echo $* | sed 's/^/$/;s/ /\" \"$/g')"
 awk '{x['"$groupby"']=x['"$groupby"']+$'$n'} END {for (a in x)print x[a],a}'
fi
