#!/usr/bin/php
<?php
$in=fopen('php://stdin',"r");
$d=array();
while($z=fgets($in))
	 @$d[$z]++;

ob_start(null, 100000);

if($argc>1 and ($argv[1]=='c' or $argv[1]=='-c'))
	foreach($d as $a=>$b)
		echo "$b $a";
else
	foreach($d as $a=>$b)
		echo $a;
