#!/usr/bin/php
<?php
$in=fopen('php://stdin',"r");
$d=array();
while($z=fgets($in))
	 @$d[$z]++;

if($argc>1 and ($argv[1]=='c' or $argv[1]=='-c'))
{
        array_walk($d, function(&$a, $b) {$a = "$a $b";});
        echo implode('', $d);
}
else
        echo implode('', array_keys($d));
